"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.swaggerDocument = exports.swaggerUi = void 0;
const express_1 = require("express");
const Paths_1 = __importDefault(require("@src/common/constants/Paths"));
const JetonRoutes_1 = __importDefault(require("./JetonRoutes"));
const FactureRoutes_1 = __importDefault(require("./FactureRoutes"));
const UtilisateursRoute_1 = __importDefault(require("./UtilisateursRoute"));
const swagger_ui_express_1 = __importDefault(require("swagger-ui-express"));
exports.swaggerUi = swagger_ui_express_1.default;
const yamljs_1 = __importDefault(require("yamljs"));
const path_1 = require("path");
const swaggerDocument = yamljs_1.default.load((0, path_1.resolve)(__dirname, '../swagger.yaml'));
exports.swaggerDocument = swaggerDocument;
const apiRouter = (0, express_1.Router)();
const tokenRouter = (0, express_1.Router)();
tokenRouter.post(Paths_1.default.GenerateToken.Get, JetonRoutes_1.default.generateToken);
apiRouter.use(Paths_1.default.GenerateToken.Base, tokenRouter);
const factureRouter = (0, express_1.Router)();
factureRouter.get(Paths_1.default.Factures.Get, FactureRoutes_1.default.getAll);
factureRouter.get(Paths_1.default.Factures.GetByNumber, FactureRoutes_1.default.getOne);
factureRouter.post(Paths_1.default.Factures.Add, FactureRoutes_1.default.add);
factureRouter.put(Paths_1.default.Factures.Update, FactureRoutes_1.default.update);
factureRouter.get(Paths_1.default.Services.GetByService, FactureRoutes_1.default.getByService);
apiRouter.use(Paths_1.default.Factures.Base, factureRouter);
const serviceRouter = (0, express_1.Router)();
serviceRouter.get(Paths_1.default.Services.GetByService, FactureRoutes_1.default.getByService);
apiRouter.use(Paths_1.default.Services.Base, serviceRouter);
const bcRouter = (0, express_1.Router)();
const fournisseurRouter = (0, express_1.Router)();
const utilisateurRouter = (0, express_1.Router)();
utilisateurRouter.get(Paths_1.default.Utilisateurs.Get, UtilisateursRoute_1.default.getAll);
utilisateurRouter.get(Paths_1.default.Utilisateurs.GetByEmail, UtilisateursRoute_1.default.getOne);
utilisateurRouter.post(Paths_1.default.Utilisateurs.Add, UtilisateursRoute_1.default.add);
utilisateurRouter.put(Paths_1.default.Utilisateurs.Update, UtilisateursRoute_1.default.update);
utilisateurRouter.get(Paths_1.default.Utilisateurs.GetByRole, UtilisateursRoute_1.default.getByRole);
apiRouter.use(Paths_1.default.Utilisateurs.Base, utilisateurRouter);
exports.default = apiRouter;
